.IPHONY:= clear

default:
	cat Makefile


serve:
	php artisan serve

update:
	composer update

install:
	composer install

clean:
	php artisan cache:clear
	php artisan view:clear
	php artisan optimize:clear
